# Generated by Django 3.2.12 on 2023-06-27 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20230627_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_accounts',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.account'),
        ),
    ]
