# Generated by Django 3.2.12 on 2023-06-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20230627_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_accounts',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_accounts',
            field=models.ManyToManyField(to='bank.Account'),
        ),
    ]
