# Generated by Django 3.2.12 on 2023-06-27 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20230627_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_accounts',
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
    ]
