# Generated by Django 3.2.12 on 2023-05-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='bank.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_account', to='bank.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_email', models.EmailField(max_length=100)),
                ('bank_accounts', models.ManyToManyField(blank=True, to='bank.Account')),
            ],
        ),
    ]
