# Generated by Django 3.2.12 on 2023-06-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20230527_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='transactions',
        ),
        migrations.AddField(
            model_name='account',
            name='transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.transaction'),
        ),
    ]
