@startuml bank_helper

'''Class diagram of a Bank Assistant that use a server-client architecture'''

class User {
    - id = string
    - username = string
    - address = string
    - phone = int
    - email = string
    - password = string
    - account = Account
    + log_in()
    + log_out()
    + register()
    + start_chat()
    + send_message()
}

class Message {
    - id = string
    - content = string
    - date = datetime
    - user = User
    - chat = Chat
}

class Chat {
    - id = string
    - chat_name = string
    - date = datetime
    - messages = Message[]
    + receive_message()
    + connect_to_bank()

}

class Bank {
    - id = string
    - bank_name = string
    - bank_email = string
    - bank_accounts = Account[]
    + get_request()
    + create_account()
    + delete_account()
    + update_account()
    + select_account()
}

class Account {
    - id = string
    - account_number = string
    - balance = float
    - transactions = Transaction[]
    + deposit()
    + withdraw()
    + transfer()
    + get_balance()
    + create_transaction()
    + cancel_transaction()
}

class Transaction {
    - id = string
    - amount = float
    - date = datetime
    - status = string
    - source_account = Account
    - destination_account = Account
}

User -d-> Message
User -r-> Chat
Chat -d-> Message
Chat -r-> Bank
Bank -d-> Account
Account -r-> Transaction

@enduml